name: Actualizar ramas desde main

on:
  push:
    branches: [ main ]

jobs:
  actualizar-ramas:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Configurar identidad de Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Fusionar main en ramas secundarias
        run: |
          # Lista de ramas que deseas actualizar
          RAMAS_DESTINO="huggingface-ai-chatbot otra-rama otra-rama-mas"
          
          for rama in $RAMAS_DESTINO; do
            echo "⏳ Actualizando $rama con los cambios de main..."
            
            # Cambiar a la rama (crea rama local si no existe)
            git checkout -B $rama origin/$rama
            
            # Obtener cambios más recientes para evitar conflictos
            git pull --no-rebase
            
            # Verificar si es necesario fusionar (validación de seguridad)
            if git merge-base --is-ancestor main $rama; then
              echo "✅ $rama ya está actualizada con main"
              continue
            fi
            
            # Intentar fusión (crea un commit de fusión)
            if git merge --no-edit --no-ff main; then
              echo "🔀 Fusión exitosa de main en $rama"
              # Enviar los cambios
              git push origin $rama
              echo "📤 Cambios enviados a $rama"
            else
              echo "⚠️ Conflicto de fusión en $rama - omitiendo"
              echo "❗ Necesitarás resolver los conflictos manualmente en $rama"
              # Solo abortar fusión si hay una en progreso
              if [ -f ".git/MERGE_HEAD" ]; then
                git merge --abort
              fi
              # Crear un issue en GitHub para notificar
              gh issue create --title "Conflicto de fusión en $rama" \
                --body "Fusión automática fallida. Por favor resuelve los conflictos entre main y $rama manualmente." \
                --label "conflicto-fusion"
            fi
          done
          
          # Volver a la rama main al finalizar
          git checkout main
